name: Compile
on: 
  workflow_dispatch: 
  pull_request:
      branches: main
jobs:
  Compilation:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: make
        working-directory: kotishell
      - run: echo "Compiled"
