name: Execute
on: 
  workflow_dispatch: 
  pull_request:
      branches: main
jobs:
  Execute-testing:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install valgrind
      - uses: actions/checkout@v3
      - run: make
        working-directory: test/ex_tests
      - run: valgrind --error-exitcode=23 --leak-check=full -s ./ex_test_string_part.exe
        working-directory: test/ex_tests
      - run: valgrind --error-exitcode=23 --leak-check=full -s ./ex_test_ls.exe
        working-directory: test/ex_tests
      - run: valgrind --error-exitcode=23 --leak-check=full -s ./ex_test_ls_grep.exe
        working-directory: test/ex_tests
      - run: echo "Execute tests complete"
