name: Expand
on: 
  workflow_dispatch: 
  pull_request:
      branches: main
jobs:
  Expansion-testing:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install valgrind
      - uses: actions/checkout@v3
      - run: make && valgrind --error-exitcode=23 --leak-check=full -s ./tk_tests
        working-directory: test/ep_tests
      - run: echo "Expand tests complete"
