name: Submit
run-name: submitting to intra
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  Submit-to-Intra:
    runs-on: ubuntu-latest
    steps:
      - uses: Oktosha/42-submit-action@v0
