name: Submit
run-name: submitting to intra
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  Submit-to-Intra:
    runs-on: ubuntu-latest
    steps:
      - run: eval `ssh-agent -s`
      - run: echo "$SSH_PRIVATE_KEY_FOR_INTRA" | ssh-add -
        env:
          SSH_PRIVATE_KEY_FOR_INTRA: ${{ secrets.SSH_PRIVATE_KEY_FOR_INTRA }}
      - run: git clone "$INTRA_REPO_URL" intra-repo
        env:
          INTRA_REPO_URL: ${{ secrets.INTRA_REPO_URL }}
      - run: ls
      - run: ls intra-repo
      - run: pwd
