name: Tokenize
on: 
  workflow_dispatch: 
  pull_request:
      branches: main
jobs:
  Tokenize-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Testing tokenize! Great tests!"
